### ISSUE TITLE
[BUG 🐞] Outline in input fields disappear on Mobile view

### ISSUE THREAD

**Issue by SrijaAdhya12** [warmachine028/next-book#26]
# Description
- In Mobile View the outline on left and right of input field disappear once cursor is placed.

# Steps to reproduce the bug:
1. Start Login/Signup in Mobile view.
2. The outline disappears across left and right of the input box. 

### Screenshots

![image](https://github.com/user-attachments/assets/dcbc8226-a4da-4f12-b618-3f81d462d0db)

**Comment by warmachine028** [comment]
Okk
